### ISSUE TITLE
I want to see which National Parks on the west coast of the United States

### ISSUE THREAD

**Issue by shervakhav** [shervakhav/Lab-3---Github#1]
**Definition of Done:**
- The application displays a list of the national parks located in the West Coast if the user chooses to do so.

**Tasks**

- [ ] Create some sort of list(?) of all West Coast located national parks.

- [ ] Create a menu that includes an option to see West Coast located national parks

- [ ] Display the parks if option is chosen
