### ISSUE TITLE
What is the weather like in the National Parks during the summer time?

### ISSUE THREAD

**Issue by shervakhav** [shervakhav/Lab-3---Github#2]
**Definition of Done:**
- The application displays the weather of each park during the seasons (summer in this case)

**Tasks**

- [ ] Create a list of the National Parks.

- [ ] Correlate the weather each year in the summer season of each National Park

- [ ] Display the weather if option chosen
