### ISSUE TITLE
I want to provide an option to display the total number of visitors, parks, and acres of the updated National parks.

### ISSUE THREAD

**Issue by shervakhav** [shervakhav/Lab-3---Github#6]
**Definition of Done**
- Updated list of National parks sorted by National park name displayed
- total number of visitors of the updated National parks displayed
- total number of acres of the updated National parks displayed

**Tasks**

- [ ] Create list (struct?) of all national park names.

- [ ] Create a variable to store total number of visitors of the updated National parks.

- [ ] Create a variable to store the total number of acres of the updated National parks.

- [ ] Display updated list of parks, total number of visitors, and total number of acres.
