### ISSUE TITLE
I want to provide an option to display the total number of acres of the updated National Parks

### ISSUE THREAD

**Issue by shervakhav** [shervakhav/Lab-3---Github#7]
**Definition of Done**
- The application displays the total number of acres of the updated National Parks

**Tasks**

- [ ] Create a list with the acres of each National Park.

- [ ] Calculate the total number of acres of each National Park

- [ ] Display the total number of acres if chosen.
