### ISSUE TITLE
I want to provide an option to display the total number of visitors of the updated National parks

### ISSUE THREAD

**Issue by shervakhav** [shervakhav/Lab-3---Github#8]
**Definition of Done**
- Display the total number of visitors of the updated National parks

**Tasks**

- [ ] Create a variable to store the number of visitors of the National parks

- [ ] Calculate the total number of visitors

- [ ] Display the total number of visitors
